#!/Users/olebogeng/anaconda3/envs/DATA-ENRICHMENT/bin/python3.11
import sys
from lib2to3.main import main

sys.exit(main("lib2to3.fixes"))
